---
- name: singularity | check Go dependencies installed
  command: 'bash -c "go list github.com/golang/dep"'
  environment:
    PATH: '{{ golang_install_dir }}/bin:{{ ansible_env.PATH }}'
    GOROOT: '{{ golang_install_dir }}'
    GOPATH: '{{ golang_gopath }}'
  register: go_installed
  changed_when: False
  failed_when: False

- name: singularity | install Go dependencies
  command: go get -u -v github.com/golang/dep/cmd/dep
  environment:
    PATH: '{{ golang_install_dir }}/bin:{{ ansible_env.PATH }}'
    GOROOT: '{{ golang_install_dir }}'
    GOPATH: '{{ golang_gopath }}'
  when:
    - not ansible_check_mode
    - go_installed.rc == 1
